### ISSUE TITLE
Add an option to pass arbitrary GH user name

### ISSUE THREAD

**Issue by yermulnik** [nedredmond/gh-role#13]
There might be use cases where `gh-role`'s functionality could be expanded to accept arbitrary GH username on the command line or via an env var (sometimes it is needed to verify programmatically someone else's access to a repo or an org). Would appreciate if this got implemented. Thanks.

**Comment by nedredmond** [comment]
I've been thinking the same! Thanks for the suggestion.

**Comment by nedredmond** [comment]
Resolved with #14

**Comment by yermulnik** [comment]
Thank you! This works, though resolves to upstream in a forked repo. Is this intentional?
```shell
> git remote -v
origin  git@github.com:yermulnik/gh-repo-collab.git (fetch)
origin  git@github.com:yermulnik/gh-repo-collab.git (push)
upstream        git@github.com:mislav/gh-repo-collab.git (fetch)
upstream        git@github.com:mislav/gh-repo-collab.git (push)

> gh role -f
yermulnik has read role in mislav/gh-repo-collab.

> gh role -u nedredmond
2023/04/29 14:19:13 unable to query nedredmond's role in mislav/gh-repo-collab: GraphQL: You do not have permission to view repository collaborators. (repository.collaborators)
```

**Comment by nedredmond** [comment]
@yermulnik, since you do not have collaborator/admin permissions in that repo, you do not have permission to view the list of collaborators.
It is a little unintuitive. I could probably add better error handling-- as in, first verifying whether you have permission to access information before allowing errors to surface.
If you'd like to create an issue to make that limitation more clear, that would be helpful, but I think analyzing arbitrary users against arbitrary repos that the viewer doesn't have permissions for beyond `read` is out of scope for the project.

**Comment by yermulnik** [comment]
@nedredmond The `gh role` was run inside `yermulnik/gh-repo-collab` which I am the only owner and admin. The repo per se is a fork of `mislav/gh-repo-collab`. So I'm a bit confused that `gh role` looks up permission in original repo rather than in current repo.

> I think analyzing arbitrary users against arbitrary repos that the viewer doesn't have permissions for beyond `read` is out of scope for the project.

While I support this for 100% (especially since this is not allowed by GH API), the issue is with the repo which I'm the owner of.

**Comment by nedredmond** [comment]
I understand now, thank you. Sorry I misread the issue before. That is indeed curious. Please make an issue.

**Comment by yermulnik** [comment]
No worries. I might have worded that too ambiguous =)
Here's the issue: https://github.com/nedredmond/gh-role/issues/16
